# For shinyapps.io - file is only used to indicate dependencies
# library(miniCRAN)
# repos <- "http://vnijs.github.io/radiant_miniCRAN/"
# pkgList <- pkgDep("radiant", repos=repos, type="source", suggests = FALSE)
# cat(paste0("library(",paste0(pkgList,collapse=")\nlibrary("),")"))

library(car)
library(MASS)
library(gridExtra)
library(AlgDesign)
library(GPArotation)
library(psych)
library(wordcloud)
library(markdown)
library(knitr)
library(ggdendro)
library(broom)
library(tidyr)
library(pryr)
library(htmlwidgets)
library(rpivotTable)
library(plyr)
library(stringr)
library(mgcv)
library(nnet)
library(pbkrtest)
library(quantreg)
library(assertthat)
library(R6)
library(Rcpp)
library(lazyeval)
library(DBI)
library(BH)
library(htmltools)
library(digest)
library(gtable)
library(reshape2)
library(scales)
library(proto)
library(RJSONIO)
library(yaml)
library(evaluate)
library(formatR)
library(highr)
library(memoise)
library(mime)
library(codetools)
library(mnormt)
library(httpuv)
library(xtable)
library(stringi)
library(RColorBrewer)
library(slam)
library(nlme)
library(Matrix)
library(lme4)
library(SparseM)
library(dichromat)
library(munsell)
library(labeling)
library(lattice)
library(minqa)
library(nloptr)
library(RcppEigen)
library(colorspace)

library(radiant)
library(lubridate)
library(ggplot2)
library(dplyr)
library(magrittr)
library(shiny)
library(shinyAce)
library(DT)
