---
title: "Radiant Install Instructions"
author: "Vincent Nijs"
date: "October 19, 2014"
output: html_document
---

<!-- 
*** DO NOT ACCEPT THE SHARED FOLDER IN THIS DROPBOX INVITE UNTIL ... ***
*** YOU READ THE INSTRUCTIONS BELOW AND COMPLETE THE STEPS IN ORDER *** 
-->

## How to install Radiant

### Step 1: Install Dropbox on your computer (the desktop version of Dropbox)

Download the Dropbox software from <https://www.dropbox.com/downloading> and install it. If you already have Dropbox installed on your computer, this step will ensure that you are running the latest version. If you do not have a Dropbox account yet, you will be asked to create one. Once you have installed Dropbox, make sure that it is running. In Windows, the icon is typically on the bottom right of the screen (i.e., the system tray). In Mac OSX, it is typically at the top of the screen in the menu bar. If Dropbox is running make sure that you are logged in with the username and password you normally use for Dropbox. For example, if you always login to Dropbox with a gmail account make sure you are logged in with that account now as well. 

### Step 2: Accept the invitation to share the dropbox folder (at the bottom of the invitation email from Dropbox) 

Accept the invitation in the email to share the Radiant folder (see the button at the bottom of the invitation e-mail). Because you are logged into Dropbox already, Dropbox will recognize that fact and it doesn't matter that this invitation was sent to your UCSD e-mail. Wait until the folder has fully synced to your computer. You may notice that the Dropbox icon changes from a green check-mark to a different form that indicates it is syncing files. 

Note that the folder is read-only. If you want to edit a file you can copy-and-paste it to another location (e.g., the Desktop).

### Step 3: Download and install R (version 3.1.1) for your operating system. 

* For Windows: http://cran.cnr.berkeley.edu/bin/windows/base/R-3.1.1-win.exe
* For Mac (10.9 aka Mavericks): http://cran.cnr.berkeley.edu/bin/macosx/R-3.1.1-mavericks.pkg
* For Mac (10.6 - 10.8): http://cran.cnr.berkeley.edu/bin/macosx/R-3.1.1-snowleopard.pkg

### Step 4: Download and install additional software for your operating system. 

For the mac:\
* http://download1.rstudio.org/RStudio-0.98.1074.dmg\
* http://mirror.ctan.org/systems/mac/mactex/mactex-basic.pkg

For windows:\
* http://download1.rstudio.org/RStudio-0.98.1074.exe\
* http://mirrors.ctan.org/systems/win32/miktex/setup/basic-miktex-2.9.5105.exe

### Step 5: Use a modern browser

We recommend that you install Chrome or Firefox for better performance. On a Mac, Safari is also fine. It will be easiest if you make Chrome, Firefox, or Safari your default browser.

* Chrome: https://www.google.com/chrome/browser/
* Firefox: https://www.mozilla.org/en-US/firefox/new/

### Step 6: Start the app

We included tools to create 'launchers' on your Desktop to make it easy to start Radiant. For the quant class (MGT 403), the tools are in the directory Dropbox/radiant/launchers/quant. For the Marketing Research class (MGT 475), the tools are in the directory Dropbox/radiant/launchers/marketing. 

For Windows, use the make\_win.bat file and for Mac the make\_win.command file. On Windows you create a launcher for Radiant on your Desktop by double-clicking the make\_win.bat file. Find the new file on your Desktop (i.e., radiant\_quant.bat or radiant_marketing.bat). Double click the .bat file and Radiant will start. The first time you start the app a number of required packages will be installed, and this may take a few minute

For Mac, double-click the make\_mac.command file to create a launcher for Radiant on your Desktop. Find the new file on your Desktop (i.e., radiant\_quant.command or radiant_marketing.command). Double click the .command file and Radiant will start. The first time you start the app a number of required packages will be installed, and this may take a few minute

If Radiant successfully launches, your browser will open and you will see the Radiant web application running inside of the browser. You should see it load data related to diamonds. To close the application click on "Quit" in the Navbar. The Radiant process will stop and you can close the browser.
