---
title: "Todo"
author: "Vincent Nijs"
date: "October 11, 2014"
output: html_document
---

Inspiration:
- David McCandless - information is beautiful - 18 minutes
- Hans Rosling - the best stats you've ever seen - 20 minutes
- http://www.r-bloggers.com/sbs-documentary-the-age-of-big-data/

0.6

Transform:
- Recode completely
- Add option to send commands to Report

Explore:
- Recode almost completely for dplyr
- Help file

Testing:
- Test using the Report feature to start 
- Test using Rselenium
- Test the (regular) function with testthat
  - There may be a way to source them without the 'no reactive context' error
  - Otherwise split them off into separate file

Filter on:
- Create separate filter tab
- https://github.com/RCura/ScattRplot using an interactive graph to filter data
- Dygraph: http://rstudio.github.io/dygraphs/index.html
- data.tables or ...
- if not data.tables maybe (1) select variables (in order) you want to filter/sort on
and (2) create dropdown, radio-buttons, sliders, etc.. Commands can be processed with 
dplyr commands
- ...
- List of filters that can be applied to data in a dropdown. Store as data.frame attribute

Viz:
- Facets can use integer, character, etc.
- Options: Cross-sectional or Time-series (and then both)
- Convert to ggvis: 
  - http://ggvis.rstudio.com/ggvis-basics.html#more-details
  - https://github.com/jimhester/ggplot2ToGgvis
  
- Dygraph for timeseries: http://rstudio.github.io/dygraphs/index.html

- Leaflet: https://github.com/jcheng5/leaflet-shiny
- Leaflet: http://www.showmeshiny.com/fracking-growth/
- Bikeshare: http://glimmer.rstudio.com/ramnathv/BikeShare/ 


Time-series:
- VARX: http://artax.karlin.mff.cuni.cz/r-help/library/fastVAR/html/fastVAR-package.html
- IRFs 
- Forecasting
- Dygraph for timeseries: http://rstudio.github.io/dygraphs/index.html

Explore:
- Can use integer, character, etc.
- Can you use all variable types for summary stats (checking required)
- Sorting or results, top/bottom 10, etc.
- Basic coding using dplyr verbs?

Output:
- regression etc. use html for model output 
  - stargazer
  - knitr's kable(rndmat, format = "markdown")
  - ...
  
Base:
- http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2064100/figure/fig5/
- http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2064100/figure/fig6/

Dependencies:
- remove plyr (reshape2?)
- remove car?
- add mosaic (see below)

Mosaic:
- Include dependency
- Resampling: http://cran.r-project.org/web/packages/mosaic/vignettes/V5Resample.pdf
- Graphics: http://cran.r-project.org/web/packages/mosaic/vignettes/GraphicsWithMosaic.html
- Calculus: http://cran.r-project.org/web/packages/mosaic/vignettes/V6Calculus.pdf
- Modeling: http://cran.r-project.org/web/packages/mosaic/vignettes/V4Modeling.pdf
- Website: http://mosaic-web.org/
- GitHub site: https://github.com/rpruim/mosaic

Rmarkdown:
- source functions from standalone Rmd
- store reports as data.frame attribute
- embedding data into Rmd file (http://bayesfactor.blogspot.com/2014/09/embedding-rdata-files-in-rmarkdown.html)
- cheatsheet link: http://rmarkdown.rstudio.com/RMarkdownCheatSheet.pdf

Coding:
- shinyAce code-completion: https://saurfang.shinyapps.io/shinyAceCodeInput/
- shinyAce vim-mode: 
- TextArea with enter to activate: https://groups.google.com/forum/#!msg/shiny-discuss/BFUgjICEQlc/fCn4sYePDhwJ

Coding style:
- Use chaining (http://timelyportfolio.github.io/rCharts_factor_analytics/factors_with_new_R.html
- dplyr:
  - http://seananderson.ca/2014/09/13/dplyr-intro.html
  - http://jimhester.github.io/plyrToDplyr/
- magitter: ..
- lintr (https://github.com/jimhester/lintr)

Merge:
- Add dropdowns so you can choose different variables from each dataset to merge on
- Add example dataset so students can see how the merges work ()





library(dplyr)

    input <- list()
    input$top3 <- "mpg"
    
    mtcars %>%
      arrange_(paste0("desc(",input$top3,")"))  %>%
      head(n=3)
      
    mtcars %>%
      arrange_(input$top3)  %>%
      tail(n=3)
 
    mtcars %>%
      arrange(desc_(input$top3)) %>%
      head(n=3)

* Update applet to include the $\beta$ parameters and the _b_ paramters. You can also show the population and sample line in the plot.

## Blog/site for Business Analytics
r 
- https://github.com/jekyll/jekyll-help/issues/44
- http://magnusmetz.github.io/
- http://magnusmetz.github.io/about.html

# Checkout Blake's slides and the menu in stata to see what they do on comparing means and proportions

## Note

For debugging having the state be dumped at a break point is really easy!!! Did that 'manually' to fix the expected values plot for cross-tabs.

## Now

- 'return' to activate textarea
- filter page to create filter drop-down


## Todo soon

MEANS!!!

- http://www.cookbook-r.com/Graphs/Plotting_means_and_error_bars_(ggplot2)/

Also, mosaic plot :  "this_base <- "fig05-08_monterey-bay-aquarium-data-mosaic-plot-preliminaries"



- Stargazer for HTML output (e.g., regression): http://www.jakeruss.com/a-stargazer-cheatsheet.html
- Lags (with dplyr), time-series, plots of predictions with confidence bounds etc. (http://f.briatte.org/teaching/ida/091_lags.html)
- Good plots for comparing means (http://www.r-bloggers.com/statistics-doesnt-have-to-be-so-hard-simulate/)
- Figure out a good way to do contrasts for comparing means and proportions (http://stat.ethz.ch/R-manual/R-patched/library/stats/html/contrast.html)
- Dplyr throughout (including lags) - http://cran.r-project.org/web/packages/dplyr/vignettes/nse.html

## Joe's input
- On quit Input and Values are dumped into Rstudio (in list rret). Add a function to save the 'statefile' from Rstudio into a location Radiant will look next time you start it up. Or it could just look in the global environment for radiantRet and read from there.
- Organize the code as suggested by Joe in https://github.com/jcheng5/shiny-partials
- Setup a local Mathjax as Joe suggested https://groups.google.com/forum/?fromgroups=#!topic/shiny-discuss/y_Plegpdlos. Or ... https://github.com/rstudio/shiny/issues/619 rely on mathjax bundeled with Rstudio

### Ideas for Yuhui

#### Interact with a Shiny app from Rstudio
* What I want ...
* What I do now. Save and Load state, using functions in radiant.R. State will be dumped into Rstudio on quit.
* Both have access to the same environment?

#### Rmarkdown with a Shiny app
- Move regular functions to separate files so they can be sourced from Rstudio and used 
in the creation of Rmarkdown documents (e.g., answer keys)
- Embed component from app into the Rmd document instead of the actual code. Click on the output to activate the UI component.

http://rmarkdown.rstudio.com/authoring_shiny.html#embedded-applications

I think it would mean transforming the app into a set of widgets that could be embedded into documents. Instead of having normal code in the document it just pops up the ui you need if you want to change something.



For me:
- How to best name the functions? Avoid putting in default (e.g., line = TRUE) terms when sent to report?


#### Save filters and apply as selected
* Access filters from renderDataTable?
* Create filter from dplyr and select from dropdown




- Can you add a report (or reports per tool) as an attribute to a data file? Seems like that should be possible right? Much like the data description file. There could be a dropdown or button on the manage page when you open a data-file that would show you reports and/or take you to edit report. 
- I guess the parameters of the state could also just be added as an attribute right? Sounds nice doesn't it. So if you are handing in an assignment you just post your data and tell the id of the attribute with your report and we can check everything from results, comments, to analysis. 
- What about if a student does several analyses and/or creates different output from one tool (e.g., multiple regressions). I guess you could save multiple 'states' that you could flip back through using a dropdown menu. This is starting to sound better and better :)

- Using state files and Rmd to get students easy access and switching between report and analysis. See also below:

From: <Nijs>, Vincent Nijs <vnijs@ucsd.edu>
Date: Monday, October 13, 2014 at 12:24 AM
To: "August, Terrence" <taugust@ucsd.edu>
Subject: Re: data exercise

Based on the conversation we just had I got some (potentially) awesome ideas :)

I agree with your view that out regular MBA students won’t be coding and/or trying to figure-out what is in the code blocks in the Rmd files. If you could basically click on one of those code blocks and it would show you the UI that was used to create the relevant output (including the setting, variables, etc.) that would be awesome. The developers of Shiny (Rstudio) have come up with the concept of dynamic documents. These are basically Rmd files with mini shiny apps embedded in them (see link below). Where I was suggesting replacing the code blocks with a set of parameters that, when a button is clicked, would open up the UI for the tool you were using this puts the fully UI in the document itself. I am not sure if that is a better idea because it could make for pretty bloated documents.

These idea remind me of Mathematica and ipython notebooks … just much more awesomer :)

http://rmarkdown.rstudio.com/authoring_shiny.html#embedded-applications

I am not sure yet what the implications would be for Radiant in its current form. I think it would mean transforming the app into a set of widgets that could be embedded into documents. Instead of having normal code in the document it just pops up the ui you need if you want to change something.


- Logging data transformations. Do a check if the original data is equal to the final data after the listed set of
transformations.


- Use new rmarkdown syntax to render Rmd files
- Can choose the type of plot for single varible (e.g., box plot or time-series or histogram)
- Button to Switch X- and Y-variable in Visualize
- Auto height for Shiny ace (https://github.com/trestletech/shinyAce/issues/18).
- Use radio buttons to specify the desired output format from rmarkdown. Would need to have Rstudio installed
to get Pandoc. Also have them install miktex or something?
- Download data from renderDataViewer into a new rda file! Ask Xie how you get to the index created by DataTables


